FROM eclipse-mosquitto


#Config Proxy
#ENV http_proxy 'http://[HOSTNAME:PORT]'
#ENV https_proxy 'https://[HOSTNAME:PORT]'
#ENV ftp_proxy 'ftp://[HOSTNAME:PORT]'
#ENV socks_proxy 'socks://[HOSTNAME:PORT]'
